/** Non-blocking questions carried by an assistant text item, not a permission RPC. */
export interface AsyncQuestionSet {
  id: string;
  questions: Array<{ title: string; options: string[] | null }>;
}

/** Correlation on an ordinary user message; delivery remains owned by its queue. */
export interface AsyncQuestionReply {
  questionId: string;
  questionIndex: number;
}

export function parseAsyncQuestionSet(value: unknown): AsyncQuestionSet | undefined {
  if (!value || typeof value !== 'object') return undefined;
  const { id, questions } = value as Record<string, unknown>;
  if (typeof id !== 'string' || !id || !Array.isArray(questions) || questions.length === 0) return undefined;
  const parsed: AsyncQuestionSet['questions'] = [];
  for (const question of questions) {
    if (!question || typeof question !== 'object') return undefined;
    const { title, options } = question as Record<string, unknown>;
    if (typeof title !== 'string' || !title.trim()) return undefined;
    if (options !== null && (!Array.isArray(options) || !options.every(option => typeof option === 'string' && option.trim()))) return undefined;
    parsed.push({ title, options: options === null ? null : [...options as string[]] });
  }
  return { id, questions: parsed };
}

export function isAsyncQuestionReply(value: unknown): value is AsyncQuestionReply {
  if (!value || typeof value !== 'object') return false;
  const reply = value as Record<string, unknown>;
  return typeof reply.questionId === 'string' && reply.questionId.length > 0
    && Number.isSafeInteger(reply.questionIndex) && (reply.questionIndex as number) >= 0;
}

export function sameAsyncQuestionReply(a: AsyncQuestionReply | undefined, b: AsyncQuestionReply): boolean {
  return a?.questionId === b.questionId && a.questionIndex === b.questionIndex;
}

/** Read only explicit structured metadata. Never infer questions from Markdown. */
export function asyncQuestionSetsInContent(content: unknown): AsyncQuestionSet[] {
  let blocks = content;
  if (typeof blocks === 'string') {
    try { blocks = JSON.parse(blocks); } catch { return []; }
  }
  if (!Array.isArray(blocks)) return [];
  return blocks.flatMap(block => {
    if (!block || block.type !== 'text') return [];
    const questions = parseAsyncQuestionSet(block.asyncQuestions);
    return questions ? [questions] : [];
  });
}

/** Restore only the exact prefix generated by the question UI, retaining correlation even if its source is paged out. */
export function restoreAsyncQuestionAnswerDraft(reply: AsyncQuestionReply, text: string, sourceContents: unknown[]): {
  reply: AsyncQuestionReply; title: string; text: string;
} {
  const title = sourceContents.flatMap(asyncQuestionSetsInContent)
    .find(set => set.id === reply.questionId)?.questions[reply.questionIndex]?.title ?? '';
  const prefix = `${title}\n\n`;
  return { reply, title, text: title && text.startsWith(prefix) ? text.slice(prefix.length) : text };
}
